### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by nikolaistraessle** [go-rel/rel#165]
Hi guys

I receive the following error if I want to migrate some changes to an already migrated database:
`Error:  adapter-exec   Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ';parseTime=True' at line 1`

**Reproduce**:

1. Start database in docker-compose
```yaml
version: '3'
services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3398:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=test
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
```
2. Create the following env-variables:
```
MYSQL_HOST=localhost
MYSQL_PORT=3398
MYSQL_USERNAME=test
MYSQL_PASSWORD=test
MYSQL_DATABASE=test
```
3. Create a new table in a migrations file
4. Start migration with `rel migrate -adapter=github.com/go-rel/rel/adapter/mysql -driver=github.com/go-sql-driver/mysql` 

Now the Step 4 will fail.
Has anyone an idea?
Many thanks
